services:
  shine-music:
    build:
      context: .
      platforms: !override
        - linux/amd64
      args:
        GOPROXY: ${SHINE_GOPROXY:-https://goproxy.cn,direct}
        DEBIAN_MIRROR: ${SHINE_DEBIAN_MIRROR:-https://mirrors.aliyun.com/debian}
        UBUNTU_MIRROR: ${SHINE_UBUNTU_MIRROR:-https://mirrors.aliyun.com/ubuntu}
    volumes: !override
      - type: bind
        source: /vol1/1000/shine-music/data
        target: /data
        bind:
          create_host_path: false
      - type: bind
        source: /vol1/1000/2.Music
        target: /music
        bind:
          create_host_path: false
      - type: bind
        source: /vol1/1000/shine-music/libraries
        target: /libraries
        bind:
          create_host_path: false
      - type: bind
        source: /vol1/1000/shine-music/cache
        target: /cache
        bind:
          create_host_path: false
